//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministracionEventos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Evento
    {
        [Display(Name = "#")]
        public int ID { get; set; }
        [Display(Name = "Titulo del evento")]
        public string Titulo { get; set; }
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
        [Display(Name = "Lugar")]
        public string Lugar { get; set; }
        [Display(Name = "Fecha del evento")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "0:MM/DD/YYYY")]
        [DataType(DataType.DateTime)]
        public System.DateTime Fecha { get; set; }
        public int UsuarioID { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
